apiVersion: v1
kind: Service
metadata:
  name: airsel-rfid-webapp-prod
  labels:
    service: airsel-rfid-webapp-prod
  name: airsel-rfid-webapp-prod
spec:
  selector:
    app: airsel-rfid-webapp-prod
  ports:
  - port: 80
    targetPort: 80