# Generated by Django 2.2.6 on 2021-06-28 06:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('operations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='workrequest',
            name='modified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='operations_workrequest_modified_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='workrequest',
            name='record_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='operations_workrequest_record_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='workorderactivitycompletionassetlocationassetlistinbound',
            name='service_histories',
            field=models.ManyToManyField(blank=True, to='operations.AssetLocationAssetListServiceHistories'),
        ),
        migrations.AddField(
            model_name='workorderactivitycompletionassetlocationassetlist',
            name='service_histories',
            field=models.ManyToManyField(blank=True, to='operations.AssetLocationAssetListServiceHistories'),
        ),
        migrations.AddField(
            model_name='workorderactivitycompletion',
            name='asset_location_asset_list',
            field=models.ManyToManyField(blank=True, to='operations.WorkOrderActivityCompletionAssetLocationAssetList'),
        ),
        migrations.AddField(
            model_name='workclass',
            name='modified_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='operations_workclass_modified_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='workclass',
            name='record_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='operations_workclass_record_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='workactivityteam',
            name='teammate',
            field=models.ManyToManyField(limit_choices_to={'user_type': 'TC'}, related_name='work_activity_teammate', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='workactivityteam',
            name='work_activity',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='work_activity_team_wa', to='operations.WorkActivity'),
        ),
        migrations.AddField(
            model_name='workactivityemployee',
            name='employee_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='employee_work_activity_employee_id', to='employee.Employee'),
        ),
        migrations.AddField(
            model_name='workactivityemployee',
            name='work_order_activity_completion_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='work_activity_emplyee_work_order_activity_completion_id', to='operations.WorkOrderActivityCompletion'),
        ),
        migrations.AddField(
            model_name='workactivity',
            name='modified_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='operations_workactivity_modified_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='workactivity',
            name='record_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='operations_workactivity_record_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='servicehistoryquestionvalidvalue',
            name='service_history_question_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='service_history_question_valid_value_service_history_id', to='operations.ServiceHistoryQuestion'),
        ),
        migrations.AddField(
            model_name='servicehistoryquestion',
            name='service_history_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='service_history_question_service_history_id', to='operations.ServiceHistory'),
        ),
        migrations.AddField(
            model_name='servicehistoriesquestions',
            name='valid_value',
            field=models.ManyToManyField(blank=True, to='operations.QuestionsValidValue'),
        ),
        migrations.AddField(
            model_name='owningorganization',
            name='modified_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='operations_owningorganization_modified_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='owningorganization',
            name='record_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='operations_owningorganization_record_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='operationalreading',
            name='modified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='operations_operationalreading_modified_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='operationalreading',
            name='record_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='operations_operationalreading_record_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='bo',
            name='modified_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='operations_bo_modified_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='bo',
            name='record_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='operations_bo_record_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='assetlocationassetlistservicehistoriesinbound',
            name='question',
            field=models.ManyToManyField(blank=True, to='operations.ServiceHistoriesQuestions'),
        ),
        migrations.AddField(
            model_name='assetlocationassetlistservicehistories',
            name='question',
            field=models.ManyToManyField(blank=True, to='operations.ServiceHistoriesQuestions'),
        ),
    ]
