# Generated by Django 2.2.6 on 2021-06-28 06:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('stocks', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('organisations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transfer',
            name='transfered_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transfer_transfered_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='reversal',
            name='reversal_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reversal_reversal_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='reversal',
            name='stock',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reversal_stock', to='stocks.Stock'),
        ),
        migrations.AddField(
            model_name='return',
            name='returned_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='return_returned_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='return',
            name='stock',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='return_stock', to='stocks.Stock'),
        ),
        migrations.AddField(
            model_name='receive',
            name='received_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='receive_receive_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='receive',
            name='stock',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='stocks.Stock'),
        ),
        migrations.AddField(
            model_name='purchase',
            name='stock_receive',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='purchase_stock_receive', to='stocks.Receive'),
        ),
        migrations.AddField(
            model_name='purchase',
            name='stock_return',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='purchase_stock_return', to='stocks.Return'),
        ),
        migrations.AddField(
            model_name='purchase',
            name='supplier',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='purchase_supplier', to='organisations.Organisation'),
        ),
        migrations.AddField(
            model_name='issuance',
            name='issuanced_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='issuance_issuanced_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='issuance',
            name='stock',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='issuance_stock', to='stocks.Stock'),
        ),
        migrations.AddField(
            model_name='dispose',
            name='disposed_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dispose_disposed_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='dispose',
            name='stock',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dispose_stock', to='stocks.Stock'),
        ),
        migrations.AddField(
            model_name='count',
            name='counted_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='count_counted_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='count',
            name='stock',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='count_stock', to='stocks.Stock'),
        ),
    ]
